### PR TITLE
add support for handling cursor pagination in API 2019-07+

### PR DESCRIPTION
**Pull request by janmyszkier**
Adding support for cursor pagination. 
example usage:

```
$productResource =  $shopify->getApi()->Product();
$products = $productResource->get(['limit'=>50]);
$nextPageProducts = $productResource->get($productResource->getNextPageParams());
/* in short: you need to reuse the resource to get the params before making another resource */**
```

### CODE REVIEW

**Comment by janmyszkier** [comment]
@tareqtms can you maybe fix the host on the travis build?

**Comment by tareqtms** [comment]
@janmyszkier 
Thanks, I will merge it after reviewing.

**Comment by joeyc002** [comment]
> Adding support for cursor pagination.
> example usage:
> 
> ```
> $productResource =  $shopify->getApi()->Product();
> $products = $productResource->get(['limit'=>50]);
> $nextPageProducts = $productResource->get($productResource->getNextPageParams());
> /* in short: you need to reuse the resource to get the params before making another resource */**
> ```

> Invalid resource name getApi

**Comment by tareqtms** [comment]
@joeyc002 
That was may be some specific code related to his project. Please modify as below:

```php
$productResource =  $shopify->Product();
$products = $productResource->get(['limit'=>50]);
$nextPageProducts = $productResource->get($productResource->getNextPageParams());
```

**Comment by joeyc002** [comment]
> @joeyc002
> That was may be some specific code related to his project. Please modify as below:
> 
> ```
> $productResource =  $shopify->Product();
> $products = $productResource->get(['limit'=>50]);
> $nextPageProducts = $productResource->get($productResource->getNextPageParams());
> ```

Thanks for this, however the array returned to "$nextPageProducts" is exactly the same as "$products". The same page is returned with both variables. I am using a test shop with 68 products / 300 variants.

**Comment by joeyc002** [comment]
I found a bug. 

ShopifyResource.php From line 600:
`    public function getNextPageParams(){
        $nextPageParams = [];
        $nextPageLink =

        parse_str($this->getUrlParams($this->getNextLink()), $nextPageParams);
        return $nextPageParams;
    }`

This will always return an empty array.

**Comment by n3o77** [comment]
@joeyc002 this works fine for me. your problem is probably related to https://github.com/phpclassic/php-shopify/pull/143

**Comment by joeyc002** [comment]
Actually I've dumped the headers, Shopify isn't returning the link. Just the below:

>  [Link] => ; rel="next"

**Comment by joeyc002** [comment]
> @joeyc002 this works fine for me. your problem is probably related to #143

Ah yes you're right! I changed to 'Link' instead of 'link' in ShopifyResource.php and this is now working.

**Comment by joeyc002** [comment]
Last question, how do you know when you've reached the end? I assumed $nextPageProducts would eventually be empty and tried to do a while loop, however it loops back to the start.

**Comment by joeyc002** [comment]
I have got this working now, 

Initially I assumed the array would return empty when it reaches the end, however not only does it loop back to the start, the items per page seems to double. This really confused me!

Instead, I now get a product count, then work out how many pages there should be, then only looped that many times. This is now working for me.

**Comment by janmyszkier** [comment]
@joeyc002 
```
$shopify->getApi()
```
is actually our own wrapper, I should've posted it. But I'm glad you have figured it out :muscle:

**Pull request merged**
