### PR TITLE
Support InventoryItem and InventoryLevel

### PR DESCRIPTION
**Pull request by alozytskyi**

### CODE REVIEW

**Comment by KiloooNL** [comment]
An example of how this new API request works would be super helpful too. I'm pulling my hair out getting around this Inventory management change.

**Comment by Baldrs** [comment]
@KiloooNL see the links to their docs in updated readme. SDK maps directly to the underlying resources exactly like they describe. Pay attention to the data required by Levels resources like `set`.

**Comment by Baldrs** [comment]
For example, to set inventory levels(you need to get $locationId and $inventoryItemId beforehand: 

```php
                $variant = $sdk->Product('<shopify product id>')
                    ->Variant('<shopify variant id>')
                    ->get();

                $levels = $sdk->InventoryLevel->get(['inventory_item_ids' => $variant['inventory_item_id']]);

                $sdk->InventoryLevel->set([
                    'inventory_item_id' => $variant['inventory_item_id'],
                    'location_id'       => $levels[0]['location_id'],
                    'available'         => 50,
                ]);
```

**Comment by tareqtms** [comment]
@alozytskyi Thanks for this. I am merging only the first commit. For the second part, I will fix it by not wrapping for all custom actions.

**Pull request merged**
